{% set name = "nengo" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nengo-{{ version }}.tar.gz
  sha256: 081945180ddd7795898bfd2092981457c9af0ef19443516b1de8911d24d0927b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.13
    - python >=3.6
    - scipy >=0.13
    - scikit-learn

test:
  imports:
    - nengo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.nengo.ai/nengo
  summary: Tools for building and simulating large-scale neural models
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
